xwcw

diff --git a/.github/workflows/pr_update.yml b/.github/workflows/pr_update.yml
--- a/.github/workflows/pr_update.yml
+++ b/.github/workflows/pr_update.yml
@@ -13,8 +13,15 @@ jobs:
         with:
           text: ${{ github.event.pull_request.title }}
           regex: '^.*JIRA-.*$'
+
+      - name: Validate Jira Prefix
+        if: ${{ steps.check-branch.outputs.match == '' }}
+        run: |
+              echo "Missing Jira Ticket!"
+              exit 1
+              
       - name: Generate Link
         if: ${{ steps.check-branch.outputs.match != '' }}
         run: |
               echo "Good name!"
-              exit 1
+              exit 0
